using System.Diagnostics.CodeAnalysis;

#pragma warning disable S103 // Lines should not be too long

[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~P:Atata.Tests.GenericCollectionAssertionsExtensions.ReferenceEqualityComparer`1.Default")]
[assembly: SuppressMessage("Design", "CA1010:Collections should implement generic interface", Justification = "<Pending>", Scope = "type", Target = "~T:Atata.Tests.TestCaseDataSource")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Atata.Tests.TriggersPage.WriteTriggerEventAttribute.Execute(Atata.TriggerContext{Atata.Tests.TriggersPage})")]
[assembly: SuppressMessage("Major Code Smell", "S103:Lines should not be too long", Justification = "<Pending>", Scope = "member", Target = "~P:Atata.Tests.ListPage.ComplexHierarchicalOrderedListWithAnyVisibilityUsingControlDefinition")]
[assembly: SuppressMessage("Critical Code Smell", "S3218:Inner class members should not shadow outer class \"static\" or type members", Justification = "<Pending>", Scope = "type", Target = "~T:Atata.Tests.TypeFinderTests.StaticSubClass.SubClass")]
[assembly: SuppressMessage("Major Code Smell", "S2326:Unused type parameters should be removed", Justification = "<Pending>", Scope = "type", Target = "~T:Atata.Tests.TypeFinderTests.StaticSubClass.InnerSubClass`1")]
[assembly: SuppressMessage("Major Code Smell", "S1144:Unused private types or members should be removed", Justification = "<Pending>", Scope = "member", Target = "~M:Atata.Tests.TriggersPage.WriteTriggerEventAttribute.Execute(Atata.TriggerContext{Atata.Tests.TriggersPage})")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "<Pending>", Scope = "member", Target = "~M:Atata.Tests.TriggersPage.WriteTriggerEventAttribute.Execute(Atata.TriggerContext{Atata.Tests.TriggersPage})")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:Atata.Tests.Expressions.ObjectExpressionStringBuilderTests.GetExpressionTestCases~System.Collections.Generic.IEnumerable{NUnit.Framework.TestCaseData}")]
[assembly: SuppressMessage("Performance", "CA1802:Use literals where appropriate", Justification = "<Pending>", Scope = "member", Target = "~F:Atata.Tests.Expressions.ImprovedExpressionStringBuilderTests.s_testFieldValue")]
[assembly: SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:Atata.Tests.Expressions.ImprovedExpressionStringBuilderTests.GetExpressionTestCases~System.Collections.Generic.IEnumerable{NUnit.Framework.TestCaseData}")]
[assembly: SuppressMessage("Minor Code Smell", "S3962:\"static readonly\" constants should be \"const\" instead", Justification = "<Pending>", Scope = "member", Target = "~F:Atata.Tests.Expressions.ImprovedExpressionStringBuilderTests.s_testFieldValue")]
[assembly: SuppressMessage("Design", "CA1024:Use properties where appropriate", Justification = "<Pending>", Scope = "member", Target = "~M:Atata.Tests.Expressions.ImprovedExpressionStringBuilderTests.StaticClass.GetBool~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1024:Use properties where appropriate", Justification = "<Pending>", Scope = "member", Target = "~M:Atata.Tests.Expressions.ImprovedExpressionStringBuilderTests.StaticClass.GetInt~System.Int32")]
[assembly: SuppressMessage("Major Code Smell", "S2743:Static fields should not be used in generic types", Justification = "<Pending>", Scope = "member", Target = "~F:Atata.Tests.DataProvision.DataVerificationProviderExtensionMethodTests.ExtensionMethodTestFixture`2.s_testSuiteData")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Atata.Tests.DataProvision.DataVerificationProviderExtensionMethodTests.ExtensionMethodTestFixture`2.GetPassFunctionsTestCases(System.String)~System.Collections.Generic.IEnumerable{NUnit.Framework.TestCaseData}")]
[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:Atata.Tests.DataProvision.DataVerificationProviderExtensionMethodTests.ExtensionMethodTestFixture`2.GetFailFunctionsTestCases(System.String)~System.Collections.Generic.IEnumerable{NUnit.Framework.TestCaseData}")]
[assembly: SuppressMessage("Naming", "CA1720:Identifier contains type name", Justification = "<Pending>", Scope = "member", Target = "~P:Atata.Tests.DataProvision.EnumerableProviderTests.TestOwner.Object")]

#pragma warning restore S103 // Lines should not be too long
