<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net462</TargetFrameworks>
    <RootNamespace>Atata</RootNamespace>
    <Version>4.0.1</Version>
    <Description>
Atata Framework is a full-featured C#/.NET test automation framework built around a powerful context-driven architecture and session-based execution model.

Atata on GitHub: https://github.com/atata-framework/atata
Atata Framework documentation: https://atata.io

Features:
- WebDriver. Provides Selenium WebDriver session functionality. Preserves all WebDriver capabilities for local, remote, and headless browser automation.
- Page object model. Provides a unique fluent page object pattern for concise, maintainable page and component definitions.
- Components. Includes a rich set of ready-to-use UI testing components for inputs, tables, lists, etc.
- Smart verification. Offers fluent assertions, aggregate checks, wait-aware verification, and built-in verification triggers.
- Triggers. Includes a set of triggers to bind with different events to extend component behavior.
- Configuration. Enables flexible settings, variables, URL templates, environment-aware run options, etc.
- Logging and reporting. Built-in customizable structured logging, screenshots, page snapshots, artifact generation, and extensible log consumer support.
- Extensible ecosystem. Features a bunch of add-ons such as Atata.HtmlValidation, Atata.NLog, Atata.AspNetCore, Atata.Testcontainers.
- Integration. Easily integrates with NUnit, xUnit, MSTest, Reqnroll via dedicated packages. Works flawlessly on CI systems like GitHub Actions, Jenkins, etc.

The package targets .NET 8.0 and .NET Framework 4.6.2.
    </Description>
    <RepositoryUrl>https://github.com/atata-framework/atata</RepositoryUrl>
    <PackageId>Atata</PackageId>
    <PackageTags>atata automation testing test selenium webdriver browser</PackageTags>
    <PackageReleaseNotes>https://atata.io/blog/2026/09/07/atata-framework-4-release/</PackageReleaseNotes>
    <PackageProjectUrl>https://atata.io</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Atata.WebDriverExtras" Version="4.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" Condition="'$(TargetFramework)' == 'net462'" />
    <PackageReference Include="PolySharp" Version="1.16.0" PrivateAssets="all" />
    <PackageReference Include="Selenium.WebDriver" Version="4.48.0" />
  </ItemGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="Atata.IntegrationTests" />
    <InternalsVisibleTo Include="Atata.UnitTests" />
  </ItemGroup>

</Project>
